# Generated by Django 3.1.4 on 2021-02-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dprsubdate', models.DateTimeField(null=True)),
                ('dpraprdate', models.DateTimeField(null=True)),
                ('amt_asked', models.FloatField()),
                ('amt_approved', models.FloatField()),
                ('amt_released', models.FloatField()),
                ('schedule', models.IntegerField(null=True)),
                ('fundcategory', models.CharField(max_length=20, null=True)),
                ('projectpath', models.CharField(max_length=600, null=True)),
                ('grant_eligible_percent', models.FloatField(null=True)),
                ('approved', models.CharField(max_length=1, null=True)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('extension', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('nodal', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('utilname', models.CharField(max_length=400, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('reqdate', models.DateTimeField(null=True)),
                ('aprdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastlogin', models.DateTimeField(null=True)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TESG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_TESG', models.IntegerField(default=0, null=True)),
                ('R_path_user', models.CharField(max_length=1000, null=True)),
                ('R_path_admin', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('TESG_filepath', models.CharField(max_length=1000, null=True)),
                ('message', models.TextField(max_length=200000, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('tesg_open', models.BooleanField(default=False)),
                ('user_tesg_date', models.TextField(max_length=20000, null=True)),
                ('admin_tesg_date', models.TextField(max_length=20000, null=True)),
                ('projid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='temp_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=200, null=True)),
                ('dprsubdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('amountasked', models.FloatField()),
                ('projectpath', models.CharField(max_length=600, null=True)),
                ('deny', models.CharField(max_length=1, null=True)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('schedule', models.IntegerField(default=0)),
                ('removed', models.CharField(max_length=1, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.users')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users'),
        ),
        migrations.CreateModel(
            name='monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
    ]
