# Generated by Django 3.1.4 on 2021-02-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aprdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='reqdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
