# Generated by Django 3.1.4 on 2021-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0002_auto_20210222_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_projects',
            name='deny',
            field=models.BooleanField(default=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='removed',
            field=models.BooleanField(default=False, max_length=1, null=True),
        ),
    ]
