# Generated by Django 3.1.4 on 2021-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0004_auto_20210302_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_projects',
            name='dprdenydate',
            field=models.DateTimeField(null=True),
        ),
    ]
