# Generated by Django 3.1.4 on 2021-03-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0005_temp_projects_dprdenydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='grant_eligible_percent',
            new_name='quantumOfFunding',
        ),
        migrations.AlterField(
            model_name='projects',
            name='amt_approved',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='amt_released',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='approved',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectpath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='projectpath',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
