# Generated by Django 3.1.4 on 2021-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0006_auto_20210305_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='notification',
            field=models.TextField(null=True),
        ),
    ]
