# Generated by Django 3.1.4 on 2021-03-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0007_users_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tpd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='amountasked',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='schedule',
            field=models.IntegerField(null=True),
        ),
    ]
