# Generated by Django 3.1.4 on 2021-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0008_auto_20210305_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='deny',
            field=models.BooleanField(default=False),
        ),
    ]
