# Generated by Django 3.1.4 on 2021-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0009_projects_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
