# Generated by Django 3.1.4 on 2021-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0010_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='approvedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='denydate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
