# Generated by Django 3.1.4 on 2021-03-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0011_auto_20210311_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESG_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TESG_no', models.IntegerField()),
                ('filepath', models.TextField(null=True)),
                ('TESG_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TESG_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_admin', models.TextField(null=True)),
                ('A_user', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('date_Q', models.DateTimeField(null=True)),
                ('date_A', models.DateTimeField(null=True)),
                ('actual_TESG_no', models.IntegerField(null=True)),
                ('final', models.BooleanField(default=False)),
                ('total_TESG', models.IntegerField(default=0, null=True)),
                ('projid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='TESG',
        ),
    ]
