# Generated by Django 3.1.4 on 2021-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0012_auto_20210311_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TESG_users',
            new_name='TESG',
        ),
    ]
