# Generated by Django 3.1.4 on 2021-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0013_auto_20210311_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='dpraprdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
