# Generated by Django 3.1.4 on 2021-03-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0014_auto_20210315_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_TESG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('req_date', models.DateTimeField(null=True)),
                ('TESG_no', models.IntegerField(null=True)),
                ('actual_TESG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.tesg_admin')),
                ('projid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='U_TESG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('res_date', models.DateTimeField(null=True)),
                ('final', models.BooleanField(default=False)),
                ('A_TESG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psdf_main.a_tesg')),
                ('projid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='tesg',
            name='projid',
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='dprdenydate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='monitoring',
        ),
        migrations.DeleteModel(
            name='TESG',
        ),
    ]
