# Generated by Django 3.1.4 on 2021-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0015_auto_20210316_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_tesg',
            name='final',
        ),
        migrations.AddField(
            model_name='a_tesg',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tesg_admin',
            name='projects',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='a_tesg',
            name='req_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tesg_admin',
            name='TESG_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='u_tesg',
            name='res_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
