# Generated by Django 3.1.4 on 2021-03-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0016_auto_20210316_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_tesg',
            name='TESG_no',
        ),
        migrations.RemoveField(
            model_name='a_tesg',
            name='final',
        ),
        migrations.AddField(
            model_name='projects',
            name='tesglist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tesg_admin',
            name='TESG_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='TESG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('final', models.BooleanField(default=False)),
                ('admintesg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.a_tesg')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('tesgnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.tesg_admin')),
                ('usertesg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.u_tesg')),
            ],
        ),
    ]
