# Generated by Django 3.1.4 on 2021-03-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0018_auto_20210317_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tesglist',
            field=models.TextField(null=True),
        ),
    ]
