# Generated by Django 3.1.4 on 2021-03-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0020_auto_20210317_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='tesglist',
            new_name='tesg_list',
        ),
    ]
