# Generated by Django 3.1.4 on 2021-03-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0022_auto_20210322_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dprsubdate', models.DateTimeField(null=True)),
                ('dpraprdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('amt_asked', models.FloatField()),
                ('amt_approved', models.FloatField(null=True)),
                ('amt_released', models.FloatField(null=True)),
                ('schedule', models.IntegerField(null=True)),
                ('fundcategory', models.CharField(max_length=20, null=True)),
                ('projectpath', models.TextField(null=True)),
                ('quantumOfFunding', models.FloatField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('extension', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(default='1', max_length=1, null=True)),
                ('approved_boq', models.TextField(null=True)),
                ('submitted_boq', models.TextField(null=True)),
                ('deny', models.BooleanField(default=False)),
                ('denydate', models.DateTimeField(null=True)),
                ('approvedate', models.DateTimeField(null=True)),
                ('tesg_list', models.TextField(null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users')),
            ],
        ),
        migrations.AddField(
            model_name='a_tesg',
            name='projid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects'),
        ),
        migrations.AddField(
            model_name='tesg',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects'),
        ),
        migrations.AddField(
            model_name='u_tesg',
            name='projid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects'),
        ),
    ]
