# Generated by Django 3.1.4 on 2021-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0024_auto_20210331_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesg',
            name='num',
        ),
        migrations.AddField(
            model_name='tesg',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
