# Generated by Django 3.1.4 on 2021-04-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0025_auto_20210331_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESG_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.TextField(null=True)),
                ('user_filepath', models.TextField(null=True)),
                ('user_res_date', models.DateTimeField(auto_now_add=True)),
                ('admin_outcome', models.TextField(null=True)),
                ('admin_filepath', models.TextField(null=True)),
                ('admin_req_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('tesgnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.tesg_admin')),
            ],
        ),
        migrations.RemoveField(
            model_name='tesg',
            name='admintesg',
        ),
        migrations.RemoveField(
            model_name='tesg',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tesg',
            name='tesgnum',
        ),
        migrations.RemoveField(
            model_name='tesg',
            name='usertesg',
        ),
        migrations.RemoveField(
            model_name='u_tesg',
            name='A_TESG',
        ),
        migrations.RemoveField(
            model_name='u_tesg',
            name='projid',
        ),
        migrations.DeleteModel(
            name='A_TESG',
        ),
        migrations.DeleteModel(
            name='TESG',
        ),
        migrations.DeleteModel(
            name='U_TESG',
        ),
    ]
