# Generated by Django 3.1.4 on 2021-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0027_remove_tesg_master_admin_req_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesg_master',
            name='user_res_date',
            field=models.DateTimeField(null=True),
        ),
    ]
