# Generated by Django 3.1.4 on 2021-06-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0028_auto_20210401_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='approved_boq',
        ),
        migrations.CreateModel(
            name='Appraisal_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projid', models.IntegerField(unique=True)),
                ('filepath', models.TextField(null=True)),
                ('appr_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
            ],
        ),
    ]
