# Generated by Django 3.1.4 on 2021-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0029_auto_20210605_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal_admin',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
