# Generated by Django 3.1.4 on 2021-07-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0030_appraisal_admin_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal_admin',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users'),
        ),
    ]
