# Generated by Django 3.1.4 on 2021-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0031_appraisal_admin_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='workflow',
            field=models.TextField(null=True),
        ),
    ]
