# Generated by Django 3.1.4 on 2021-07-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0032_projects_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal_admin',
            old_name='appr_date',
            new_name='apprdate',
        ),
        migrations.RenameField(
            model_name='appraisal_admin',
            old_name='filepath',
            new_name='apprpath',
        ),
        migrations.RemoveField(
            model_name='appraisal_admin',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='appraisal_admin',
            name='userid',
        ),
        migrations.CreateModel(
            name='Monitoring_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projid', models.IntegerField(unique=True)),
                ('remarks', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('moni_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users')),
            ],
        ),
    ]
