# Generated by Django 3.1.4 on 2021-07-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0033_auto_20210707_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring_admin',
            old_name='moni_date',
            new_name='monidate',
        ),
        migrations.RenameField(
            model_name='monitoring_admin',
            old_name='filepath',
            new_name='monipath',
        ),
        migrations.RemoveField(
            model_name='appraisal_admin',
            name='projid',
        ),
        migrations.RemoveField(
            model_name='monitoring_admin',
            name='projid',
        ),
        migrations.RemoveField(
            model_name='monitoring_admin',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='monitoring_admin',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='extension',
        ),
    ]
