# Generated by Django 3.1.4 on 2021-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0035_auto_20210709_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='appraprdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='finalaprdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='moniaprdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='tesgaprdate',
            field=models.DateTimeField(null=True),
        ),
    ]
