# Generated by Django 3.1.4 on 2021-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0036_auto_20210709_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='projectpath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='temp_projects',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
