# Generated by Django 3.1.4 on 2021-07-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0038_auto_20210723_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='newid',
            field=models.IntegerField(null=True),
        ),
    ]
