# Generated by Django 3.1.4 on 2021-07-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0039_projects_newid'),
    ]

    operations = [
        migrations.CreateModel(
            name='boq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boqtype', models.IntegerField(null=True)),
                ('itemno', models.IntegerField(null=True)),
                ('itemname', models.TextField(null=True)),
                ('itemdesc', models.TextField(null=True)),
                ('itemqty', models.IntegerField(null=True)),
                ('unitcost', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
    ]
