# Generated by Django 3.1.4 on 2021-07-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0040_boq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='newid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
