# Generated by Django 3.1.4 on 2021-07-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0042_auto_20210724_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boq',
            new_name='boqdata',
        ),
    ]
