# Generated by Django 3.1.4 on 2021-07-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0043_auto_20210725_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqdata',
            name='itemno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boqdata',
            name='itemqty',
            field=models.IntegerField(null=True),
        ),
    ]
