# Generated by Django 3.1.4 on 2021-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0044_auto_20210725_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='doc_path',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='loadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.IntegerField(default=0, null=True)),
                ('req_boq', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('subdate', models.DateField(auto_now_add=True, null=True)),
                ('compdate', models.DateField(null=True)),
                ('approved', models.CharField(default=2, max_length=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
    ]
