# Generated by Django 3.1.4 on 2021-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0045_auto_20210916_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='doc_sign_date',
            field=models.DateField(null=True),
        ),
    ]
